### ISSUE TITLE
Caching policy needed.

### ISSUE THREAD

**Issue by Sugarsplash** [Sugarsplash/ece485#2]
Here is my proposal, 

If we evict the lowest value tag, we will essentially be implementing FIFO. Not the greatest caching scheme, but alas the only one I can think of that will not require tracking more info in memory. 
I will implement this one, but I am reaching out for alternative implementations. 

Is there any way to use the remaining 40bits of M1 to track data for another schema?
Can we squeeze more free bits out of M1 controller and is it worth it?

**Comment by vertexmachina** [comment]
The lines of M1 currently have 8 bits for the tag when we only need 6 (or
was it 5?), and 8 bits for Next when we only need 7 (80 lines). That's
three spare bits we could use for an Age field. Every time a transaction
occurs, if a cache line isn't read/written then its age increases by one.
If it is read/written its age is reset to 0.

When looking for a place to evict it just needs to find the oldest age (max
age being 7) and evict that one.

This would be a more advanced LRU.

**Comment by daj3** [comment]
We only need to reserve 5 bits for the tag. If we only need 7 bits for our Next field, we'll have 4 other bits to work with (max age of 15).

How might we use the replacement system when given a large number of 128 byte transactions? If we assume 16 of these transactions have taken place (2048 bytes), the first transaction would have its age counter maxed. We would still need over 8 1024 byte transactions to take place to fill the memory (10240 bytes max) and cause our replacement policy to take place, meaning 9 of our cache lines would have their Age field at 15. Should we just replace the first max age field we encounter? [Actually as it turns out, we won't even fill the entirety of the memory with the second csv file that has all of those 128 byte transactions. Might not need to worry about this.]

Size of our memory = 10240 bytes

Size of first csv file = (3 \* 128) + (1 \* 512) + (13 \* 1024) = 14208 bytes
Size of second csv file = (27 \* 128) + (3 \* 1024) = 7552 bytes
Size of third csv file = 16 \* 1024 = 16384 bytes

I believe we also wanted to try replacing a cache line that is the same size. This would definitely help with making sure we don't have large gaps in our memory (For instance, if a 128 byte transaction replaces a 1024 byte block of memory).
